input {
  kafka {
    bootstrap_servers => "kafka:9093"
    topics => ["cryptodata"]
    group_id => "logstash-cryptodata"
    auto_offset_reset => "earliest"
    codec => "json"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "cryptodata"
  }
}
