input {
  kafka {
    bootstrap_servers => "kafka:9093"
    topics => ["registered_user"]
    group_id => "logstash-group"
    auto_offset_reset => "earliest"
    codec => "json" # This ensures Logstash parses the JSON correctly
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "registered_user"
  }
}